
version: "3.9"
services:
  web:
    image: frontend
    build: ../frontend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "3000:3000"
    environment:
      FRONTEND_SERVER_PORT: "3000"
    volumes:
      - ./../frontend/src:/usr/src/app/src
      - ./../frontend/public:/usr/src/app/public
      - ./../frontend/index.html:/usr/src/app/index.html
      - ./../frontend/tailwind.config.js:/usr/src/app/tailwind.config.js
      - ./../frontend/vite.config.js:/usr/src/app/vite.config.js
      - ./../frontend/postcss.config.js:/usr/src/app/postcss.config.js
      - ./../frontend/package.json:/usr/src/app/package.json
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=db_ronin
    ports:
      - "5444:5432"
  backend:
    image: backend
    volumes:
    - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh
    - ./start-backend.sh:/usr/src/app/start-backend.sh
    build: ../backend
    environment:
     - DEV_DB_HOST=db
    ports:
     - "8080:8080"
    depends_on:
     - "db"
    restart: "always"

    command: ["bash", "./start-backend.sh"]

